services:
  - type: web
    name: youtube-downloader-api
    env: node
    region: singapore
    plan: free
    buildCommand: npm install
    startCommand: node server.js
    envVars:
      - key: NODE_VERSION
        value: 20.8.0
      - key: PORT
        value: 10000
      - key: YTDL_NO_UPDATE
        value: 1
      - key: NODE_ENV
        value: production
      - key: USE_IPV6
        value: "true"
      - key: PROXY_URL
        value: ""
      - key: YOUTUBE_COOKIES
        value: ""
